config/routes.rb
Rails.application.routes.draw do
  resources :lectures do 
    member do
      post 'toggle_student_attendance'
    end
  end
  resources :students

  root 'lectures#index'

end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
  has_many :students, through: :student_lectures
  has_many :student_lectures
  
  has_many :student_attendances

acts_as_xlsx

end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/models/student_attendance.rb
class StudentAttendance < ActiveRecord::Base
  belongs_to :student
  belongs_to :lecture
  
  def change_present!
    if self.present == nil
      self.present = true
    elsif self.present == true
      self.present = false
    elsif self.present == false
      self.present = nil
    end
    
    self.save
  end  
end

app/models/student_lecture.rb
class StudentLecture < ActiveRecord::Base
  belongs_to :student
  belongs_to :lecture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  before_action :set_lecture, only: [:show, :edit, :update, :destroy]

  # GET /lectures
  # GET /lectures.json
  def index
    @lectures = Lecture.all
  
      respond_to do |format|
      format.html
      format.xlsx
      end

  end

  # GET /lectures/1

  # GET /lectures/1.json
  def show
  end

  # GET /lectures/new
  def new
    @lecture = Lecture.new
  end

  # GET /lectures/1/edit
  def edit
  end

  # POST /lectures
  # POST /lectures.json
  def create
    @lecture = Lecture.new(lecture_params)

    respond_to do |format|
      if @lecture.save
        format.html { redirect_to @lecture, notice: 'Lecture was successfully created.' }
        format.json { render :show, status: :created, location: @lecture }
      else
        format.html { render :new }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lectures/1
  # PATCH/PUT /lectures/1.json
  def update
    respond_to do |format|
      if @lecture.update(lecture_params)
        format.html { redirect_to @lecture, notice: 'Lecture was successfully updated.' }
        format.json { render :show, status: :ok, location: @lecture }
      else
        format.html { render :edit }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lectures/1
  # DELETE /lectures/1.json
  def destroy
    @lecture.destroy
    respond_to do |format|
      format.html { redirect_to lectures_url, notice: 'Lecture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def toggle_student_attendance
    @lecture = Lecture.find(params[:id])
    @student = Student.find(params[:student_id])
    @lesson_time = params[:lesson_time]

    @attendance = StudentAttendance.where(lecture_id: @lecture.id, student_id: @student.id, lesson_time: @lesson_time).first
    if @attendance
      @attendance.change_present!
    else
      @attendance = StudentAttendance.create(lecture_id: @lecture.id, student_id: @student.id, lesson_time: @lesson_time, present: true)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lecture
      @lecture = Lecture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lecture_params
      params.require(:lecture).permit(:name, :lesson_time_number)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def present_link_text(student_attendance)  
    if student_attendance == nil || student_attendance.present == nil
      image_tag('n.png')
    elsif student_attendance.present == true
      image_tag('o.png')
    elsif student_attendance.present == false
      image_tag('x.png')
    end
  end 
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ForYou</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lectures/_form.html.erb
<%= form_for(@lecture) do |f| %>
  <% if @lecture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

      <ul>
      <% @lecture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lesson_time_number %><br>
    <%= f.number_field :lesson_time_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lectures/edit.html.erb
<h1>Editing lecture</h1>

<%= render 'form' %>

<%= link_to 'Show', @lecture %> |
<%= link_to 'Back', lectures_path %>

app/views/lectures/index.html.erb
<h1>Listing lectures</h1>
<%= link_to "Download as Excel", lectures_path(format: "xlsx") %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lesson time number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lectures.each do |lecture| %>
      <tr>
        <td><%= lecture.name %></td>
        <td><%= lecture.lesson_time_number %></td>
        <td><%= link_to 'Show', lecture %></td>
        <td><%= link_to 'Edit', edit_lecture_path(lecture) %></td>
        <td><%= link_to 'Destroy', lecture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lecture', new_lecture_path %>

app/views/lectures/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Release Date</Data></Cell>

      </Row>
    <% @lectures.each do |lecture| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= lecture.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lecture.name %></Data></Cell>
       
  
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/lectures/new.html.erb
<h1>New lecture</h1>

<%= render 'form' %>

<%= link_to 'Back', lectures_path %>

app/views/lectures/show.html.erb
<p id="notice"><%= notice %></p>
<p>


</p>
<p>
  <strong>Name:</strong>
  <%= @lecture.name %>
</p>

<h2>수강생</h2>
<table class="gridtable">
    <thead>
      <tr>
        <td>학생 이름</td>        
        <% @lecture.lesson_time_number.times do |time| %>
        <td><%= "#{time + 1}차" %></td>
        <% end %>
      </tr>
    </thead>
    
    <tbody>
      <% @lecture.students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <% @lecture.lesson_time_number.times do |time| %>
        <td>
          <%= link_to toggle_student_attendance_lecture_path(@lecture, student_id: student.id, lesson_time: time), method: :post, remote: true, id: "present_link_#{@lecture.id}_#{student.id}_#{time}" do %>
            <% sa = @lecture.student_attendances.where(student_id: student.id, lesson_time: time).first %>
            <%= present_link_text(sa) %>
          <% end %>
        </td>
        <% end %>
      </tr>
    <% end %>      
    </tbody>
</table>

<%= link_to 'Edit', edit_lecture_path(@lecture) %> |
<%= link_to 'Back', lectures_path %>

app/views/lectures/toggle_student_attendance.js.erb
$("#present_link_<%= @lecture.id %>_<%= @student.id %>_<%= @lesson_time %>").html("<%= j present_link_text(@attendance) %>");
$("#present_link_<%= @lecture.id %>_<%= @student.id %>_<%= @lesson_time %>").effect("highlight");

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>